export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLE_ALL_TODO = 'TOGGLE_ALL_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_MODE_TOGGLE = 'EDIT_MODE_TOGGLE';
export const EDIT_TODO = 'EDIT_TODO';
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO';
export const SET_TODO_FILTER = 'SET_TODO_FILTER';
